// <auto-generated />
namespace DPSapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodaniepomocnejzmiennejdoUsera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodaniepomocnejzmiennejdoUsera));
        
        string IMigrationMetadata.Id
        {
            get { return "202109191912144_Dodanie pomocnej zmiennej do Usera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
